//! Resolution of the WIT sources a crate's bindings are generated from: the bundled SDK
//! prelude, the compiled packages of the `miden-project.toml` dependencies, and the crate's
//! local `wit/` directory.

use std::{
    env, fs,
    io::ErrorKind,
    path::{Path, PathBuf},
};

use proc_macro2::Span;
use syn::Error;

use crate::{
    dependency_package::{DependencyWitSource, collect_dependency_wit_sources},
    util::bundled_wit_folder,
    wit_world::ProjectPackageMetadata,
};

/// File name for the embedded Miden SDK WIT.
const SDK_WIT_FILE_NAME: &str = "miden.wit";

/// Embedded Miden SDK WIT source.
pub(crate) const SDK_WIT_SOURCE: &str = include_str!("../wit/miden.wit");

/// WIT metadata extracted from the consuming crate.
pub(crate) struct ResolvedWit {
    /// The SDK prelude directory, loaded before any dependency source.
    ///
    /// Always present in macro expansion; `None` models a self-contained fixture in tests.
    pub prelude_dir: Option<String>,
    /// WIT sources read from the compiled packages of Miden dependencies.
    pub dependency_sources: Vec<DependencyWitSource>,
    /// The compiler-written artifact map the dependency resolution consumed, when present.
    ///
    /// Tracked as a build input alongside the packages it selects.
    pub dependency_artifact_map: Option<PathBuf>,
    /// The crate's local `wit/` directory, loaded after the dependency sources so its WIT can
    /// import the dependency packages.
    pub local_wit_root: Option<PathBuf>,
    /// The `package/world` id detected in the local WIT directory, used for wit-bindgen world
    /// selection.
    pub world: Option<String>,
    /// The world-defining local WIT file, present when it is the crate's only WIT file and can
    /// therefore be embedded verbatim as the component's public WIT.
    pub embeddable_local_wit: Option<PathBuf>,
}

#[derive(Default)]
pub(crate) struct ResolveOptions {
    pub allow_missing_local_wit: bool,
}

/// Resolves the bundled SDK prelude alone, without dependency or local WIT sources.
///
/// For an inline world a macro renders entirely from its own input — the `#[component_storage]`
/// stored-procedure world — the SDK core types are the only sources it can reference. Leaving the
/// dependency packages out keeps their `.masp` files off the expansion's build inputs, so neither
/// a dependency rebuild nor a package-cache rotation re-expands the macro.
pub(crate) fn resolve_sdk_wit() -> Result<ResolvedWit, Error> {
    Ok(ResolvedWit {
        prelude_dir: Some(sdk_prelude_dir()?),
        dependency_sources: Vec::new(),
        dependency_artifact_map: None,
        local_wit_root: None,
        world: None,
        embeddable_local_wit: None,
    })
}

/// Collects WIT search paths and the target world from `miden-project.toml` + local files.
pub(crate) fn resolve_wit_paths(options: ResolveOptions) -> Result<ResolvedWit, Error> {
    let manifest = ProjectPackageMetadata::load_or_default(Span::call_site())?;

    let prelude_dir = sdk_prelude_dir()?;

    // Dependency WIT is read from each dependency's compiled `.masp` package rather than
    // from files on disk; the sources are pushed into the wit-bindgen resolver alongside the
    // file-based paths collected here. Dependencies without WIT are link-only and contribute
    // nothing to bindings generation.
    let collected = collect_dependency_wit_sources(&manifest.manifest_dir, &manifest.package)?;

    let raw_local_wit_root = Path::new(&manifest.manifest_dir).join("wit");
    let mut local_wit_root = None;
    let mut world = None;
    let mut embeddable_local_wit = None;

    if raw_local_wit_root.exists() && !options.allow_missing_local_wit {
        let local_root = fs::canonicalize(&raw_local_wit_root).unwrap_or(raw_local_wit_root);
        if let Some(local_world) = detect_world(&local_root)? {
            world = Some(local_world.world);
            embeddable_local_wit = local_world.embeddable_file;
        }
        local_wit_root = Some(local_root);
    }

    Ok(ResolvedWit {
        prelude_dir: Some(prelude_dir),
        dependency_sources: collected.sources,
        dependency_artifact_map: collected.artifact_map_path,
        local_wit_root,
        world,
        embeddable_local_wit,
    })
}

/// Materializes the bundled SDK WIT and returns its directory as a UTF-8 path.
fn sdk_prelude_dir() -> Result<String, Error> {
    let canonical_prelude_dir = ensure_sdk_wit()?;

    canonical_prelude_dir
        .to_str()
        .ok_or_else(|| {
            Error::new(
                Span::call_site(),
                format!("path '{}' contains invalid UTF-8", canonical_prelude_dir.display()),
            )
        })
        .map(str::to_owned)
}

/// Ensures the embedded Miden SDK WIT is materialized in the project's folder.
fn ensure_sdk_wit() -> Result<PathBuf, Error> {
    let autogenerated_wit_folder = bundled_wit_folder()?;

    let sdk_wit_path = autogenerated_wit_folder.join(SDK_WIT_FILE_NAME);
    let sdk_version: &str = env!("CARGO_PKG_VERSION");
    let expected_source = format!(
        "/// NOTE: This file is auto-generated from the Miden SDK.\n/// Version: \
         v{sdk_version}\n/// Any manual edits will be overwritten.\n\n{SDK_WIT_SOURCE}"
    );
    let should_write_wit = match fs::read_to_string(&sdk_wit_path) {
        Ok(existing) => existing != expected_source,
        Err(err) if err.kind() == ErrorKind::NotFound => true,
        Err(err) => {
            return Err(Error::new(
                Span::call_site(),
                format!("failed to read '{}': {err}", sdk_wit_path.display()),
            ));
        }
    };

    if should_write_wit {
        fs::write(&sdk_wit_path, expected_source).map_err(|err| {
            Error::new(
                Span::call_site(),
                format!("failed to write '{}': {err}", sdk_wit_path.display()),
            )
        })?;
    }

    Ok(fs::canonicalize(&autogenerated_wit_folder).unwrap_or(autogenerated_wit_folder))
}

/// A world detected in the crate's local `wit` directory.
struct LocalWorld {
    /// `package/world` id used for wit-bindgen world selection.
    world: String,
    /// The world-defining WIT file, present when it is the directory's only WIT file and can
    /// therefore be embedded verbatim as the component's public WIT.
    embeddable_file: Option<PathBuf>,
}

/// Scans the component's `wit` directory to find the default world.
fn detect_world(wit_root: &Path) -> Result<Option<LocalWorld>, Error> {
    let wit_files = crate::util::wit_files_in_dir(wit_root)?;

    for path in &wit_files {
        if let Some((package, world)) = parse_package_and_world(path)? {
            let embeddable_file = (wit_files.len() == 1).then(|| path.clone());
            return Ok(Some(LocalWorld {
                world: format!("{package}/{world}"),
                embeddable_file,
            }));
        }
    }

    Ok(None)
}

/// Parses a WIT source file for its package declaration and first world definition.
fn parse_package_and_world(path: &Path) -> Result<Option<(String, String)>, Error> {
    let contents = fs::read_to_string(path).map_err(|err| {
        Error::new(
            Span::call_site(),
            format!("failed to read WIT file '{}': {err}", path.display()),
        )
    })?;

    let package = extract_package_name(&contents);
    let world = extract_world_name(&contents);

    match (package, world) {
        (Some(package), Some(world)) => Ok(Some((package, world))),
        _ => Ok(None),
    }
}

/// Returns the package identifier from a WIT source string, if present.
///
/// Token-based through the shared scanner in the contract crate, so comments (line and
/// block), tabs, and multi-line declarations are all handled the same way the embedding
/// count gate and the Wasm frontend handle them. The `@<version>` suffix is stripped for
/// the `package/world` selection spelling.
fn extract_package_name(contents: &str) -> Option<String> {
    let first = midenc_frontend_wasm_metadata::top_level_wit_packages(contents)
        .into_iter()
        .next()?;
    let name = first.split('@').next().unwrap_or(first.as_str()).trim();
    if name.is_empty() {
        None
    } else {
        Some(name.to_string())
    }
}

/// Extracts the first top-level world identifier from a WIT source string.
pub(crate) fn extract_world_name(contents: &str) -> Option<String> {
    midenc_frontend_wasm_metadata::first_top_level_wit_world(contents)
}
