//! Sibling component call tests: components of one account calling each other.
//!
//! The caller component declares the sibling component package(s) as dependencies and reaches
//! them through the traits generated by `#[component(pkg::Interface, ...)]`. Unlike the FPI
//! tests, the call target is part of the transaction's native account: the calls cross the Wasm
//! component-model boundary as direct cross-context `call`s, and storage writes made by the
//! sibling commit to the account.

mod common;
mod multi_sibling;
mod sibling_and_fpi;
mod single_sibling;

use miden_client::Word;
use miden_core::Felt;

/// Returns the non-zero storage key used by the sibling counter fixtures.
///
/// Shared with the stored-procedure fixtures, which drive the same counter component.
pub(crate) fn counter_storage_key() -> Word {
    Word::new([
        Felt::new(13).unwrap(),
        Felt::new(21).unwrap(),
        Felt::new(34).unwrap(),
        Felt::new(55).unwrap(),
    ])
}
