[package]
name = "midenc-hir-symbol"
description = "Symbols for the Midend compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]

[build-dependencies]
Inflector.workspace = true
rustc-hash.workspace = true
toml.workspace = true
