[workspace]
resolver = "2"
members = [
  "codegen/*",
  "hir",
  "hir-parser",
  "hir-analysis",
  "hir-pass",
  "hir-symbol",
  "hir-transform",
  "hir-type",
  "tools/*",
  "frontend-wasm",
  "tests/rust-wasm-tests"
]

[workspace.package]
version = "0.1.0"
rust-version = "1.71"
authors = ["Miden Team"]
description = "An intermediate representation and compiler for Miden Assembly"
repository = "https://github.com/0xPolygonMiden/miden-ir"
homepage = "https://github.com/0xPolygonMiden/miden-ir"
documentation = "https://github.com/0xPolygonMiden/miden-ir"
categories = ["Compilers"]
keywords = ["compiler", "miden"]
license = "MIT"
readme = "README.md"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1.0"
bitflags = "1.3"
clap = { version = "4.1", features = ["derive"] }
cranelift-entity = "0.100"
cranelift-bforest = "0.100"
env_logger = "0.9"
intrusive-collections = "0.9"
log = "0.4"
paste = "1.0"
parking_lot = "0.12"
parking_lot_core = "0.9"
pretty_assertions = "1.0"
rustc-hash = "1.1"
smallvec = { version = "1.9", features = [
  "union",
  "const_generics",
  "const_new",
] }
smallstr = { version = "0.3", features = ["union"] }
thiserror = "1.0"
miden-assembly = "0.7"
miden-codegen-masm = { path = "codegen/masm" }
miden-diagnostics = "0.1"
miden-hir = { path = "hir" }
miden-hir-analysis = { path = "hir-analysis" }
miden-hir-pass = { path = "hir-pass" }
miden-hir-symbol = { path = "hir-symbol" }
miden-hir-transform = { path = "hir-transform" }
miden-hir-type = { path = "hir-type" }
miden-parsing = "0.1"
miden-frontend-wasm = { path = "frontend-wasm" }

[profile.release]
opt-level = 2
lto = false
