[workspace]
# Only publish when the release PR is merged
# https://release-plz.ieni.dev/docs/config#the-release_always-field
release_always = false
# Creates the release PR with the draft status
pr_draft = true
