edition = "2021"
array_width = 80
chain_width = 80
comment_width = 100
wrap_comments = false
fn_call_width = 80
reorder_modules = true
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
hex_literal_case = "Lower"
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
tab_spaces = 4
condense_wildcard_suffixes = true
format_strings = true
