//! Integration tests for note storage schemas stored in Miden packages.

use std::sync::Arc;

use miden_mast_package::{Package, SectionId};
use midenc_expect_test::{Expect, expect};
use midenc_frontend_wasm::WasmTranslationConfig;
use midenc_frontend_wasm_metadata::PACKAGE_NOTE_STORAGE_SCHEMA_SECTION_ID;
use wit_bindgen_core::wit_parser::{Resolve, Type as WitType, TypeDefKind};

use crate::CompilerTest;

/// Disables debug output so compiled package content is stable.
fn no_debug_flags() -> [String; 2] {
    ["--debug".to_string(), "none".to_string()]
}

/// Compiles one project with the Cargo Miden frontend.
fn compile_project(project_path: &str) -> Arc<Package> {
    let mut test = CompilerTest::rust_source_cargo_miden(
        project_path,
        WasmTranslationConfig::default(),
        no_debug_flags(),
    );
    test.compile_package()
}

/// Returns the unpadded note storage schema text from a package.
fn note_storage_schema(package: &Package) -> &str {
    let section_id = SectionId::custom(PACKAGE_NOTE_STORAGE_SCHEMA_SECTION_ID)
        .expect("schema section id must be valid");
    let bytes = package
        .sections
        .iter()
        .find(|section| section.id == section_id)
        .expect("package must contain a note storage schema")
        .data
        .as_ref();
    assert_eq!(bytes.len() % 16, 0, "schema payload must use 16-byte padding");
    let len = bytes.iter().rposition(|byte| *byte != 0).map_or(0, |index| index + 1);
    str::from_utf8(&bytes[..len]).expect("note storage schema must be UTF-8")
}

/// Checks a schema golden and resolves its root storage alias with wit-parser.
fn assert_note_storage_schema(package: &Package, expected_root: &str, expected: Expect) {
    let source = note_storage_schema(package);
    expected.assert_eq(source);

    let mut resolve = Resolve::default();
    let package_id = resolve
        .push_str("note-schema.wit", source)
        .expect("note storage schema must resolve");
    let schema_package = &resolve.packages[package_id];
    let interface_id = schema_package.interfaces["note-storage"];
    let interface = &resolve.interfaces[interface_id];
    let storage_id = interface.types["storage"];
    let TypeDefKind::Type(WitType::Id(root_id)) = resolve.types[storage_id].kind else {
        panic!("storage must be a named type alias");
    };
    assert_eq!(resolve.types[root_id].name.as_deref(), Some(expected_root));
}

#[test]
fn note_packages_carry_resolvable_storage_schema_metadata() {
    let p2id = compile_project("../../examples/p2id-note");
    assert_note_storage_schema(
        &p2id,
        "p2id-note",
        expect![[r#"
        // This file is auto-generated by the `#[note]` macro.
        // Do not edit this file manually.

        package miden:p2id-schema@0.1.0;

        use miden:base/core-types@1.0.0;

        interface note-storage {
            use core-types.{account-id};

            record p2id-note {
                target-account-id: account-id,
            }

            type storage = p2id-note;
        }

        package miden:base@1.0.0 {
            interface core-types {
                /// Represents an on-chain felt.
                ///
                /// Field modulus M = 2^64 - 2^32 + 1.
                record felt {
                    /// The backing type is `f32` which will be treated as a felt by the compiler.
            	/// We're basically hijacking the Wasm `f32` type and treat as felt.
                    inner: f32,
                }


                /// A group of four field elements in the Miden base field.
                record word {
                    a: felt,
            	b: felt,
            	c: felt,
            	d: felt,
                }

                /// A cryptographic digest representing a 256-bit hash value.
                /// This is a wrapper around `word` which contains 4 field elements.
                record digest {
                    inner: word
                }

                /// Unique identifier of an account.
                ///
                /// # Layout
                ///
                /// An `AccountId` consists of two field elements, where the first is called the prefix and the
                /// second is called the suffix. It is laid out as follows:
                ///
                /// prefix: [hash (56 bits) | storage mode (2 bits) | type (2 bits) | version (4 bits)]
                /// suffix: [zero bit | hash (55 bits) | 8 zero bits]
                record account-id {
                	prefix: felt,
            	suffix: felt
                }

                /// Creates a new account ID from a field element.
                //account-id-from-felt: func(felt: felt) -> account-id;

                /// Recipient of the note, i.e., hash(hash(hash(serial_num, [0; 4]), note_script_hash), input_hash)
                record recipient {
                    inner: word
                }

                record tag {
                    inner: felt
                }

                /// A fungible or a non-fungible asset.
                ///
                /// In protocol v0.14 assets are encoded as two words: an asset key and an asset value.
                ///
                /// The methodology for constructing fungible and non-fungible assets is described below.
                ///
                /// # Fungible assets
                /// - `key`: `[0, 0, faucet_id_suffix, faucet_id_prefix]`
                /// - `value`: `[amount, 0, 0, 0]`
                ///
                /// # Non-fungible assets
                /// - `key`: `[hash0, hash1, faucet_id_suffix, faucet_id_prefix]`
                /// - `value`: `DATA_HASH`
                record asset {
                    key: word,
                    value: word,
                }

                /// A validated fungible asset amount, at most 2^63 - 2^31.
                record asset-amount {
                    inner: felt
                }

                /// Account nonce
                record nonce {
                    inner: felt
                }

                /// A block height in the chain
                record block-number {
                    inner: felt
                }

                /// Account hash
                record account-hash {
                    inner: word
                }

                /// Block hash
                record block-hash {
                    inner: word
                }

                /// Storage value
                record storage-value {
                    inner: word
                }

                /// Account storage root
                record storage-root {
                    inner: word
                }

                /// Account code root
                record account-code-root {
                    inner: word
                }

                /// Commitment to the account vault
                record vault-commitment {
                    inner: word
                }

                /// An index of the created note
                record note-idx {
                    inner: felt
                }

                record note-type {
                    inner: felt
                }

                record note-execution-hint {
                    inner: felt
                }

            }
        }
    "#]],
    );

    let swapp = compile_project("../fixtures/components/swapp-note");
    assert_note_storage_schema(
        &swapp,
        "swapp-note",
        expect![[r#"
        // This file is auto-generated by the `#[note]` macro.
        // Do not edit this file manually.

        package miden:swapp-note-schema@0.1.0;

        use miden:base/core-types@1.0.0;

        interface note-storage {
            use core-types.{account-id, felt, word};

            /// SWAPP note storage.
            ///
            /// The note creator stores the swap terms in the note storage; the fields below are decoded
            /// from the storage elements in declaration order.
            record swapp-note {
                /// Vault key identifying the requested asset (faucet id, composition, callback flags).
                requested-asset-key: word,
                /// Total requested asset amount for the full offer.
                requested-total: felt,
                /// The account that created the swap offer and receives the requested asset.
                creator: account-id,
                /// Note type used for the notes created by this script (P2ID routing note and remainder
                /// SWAPP note).
                output-note-type: felt,
                /// Tag routing the P2ID note to the creator.
                p2id-tag: felt,
                /// Script root of the P2ID note script used for the routing note.
                p2id-script-root: word,
            }

            type storage = swapp-note;
        }

        package miden:base@1.0.0 {
            interface core-types {
                /// Represents an on-chain felt.
                ///
                /// Field modulus M = 2^64 - 2^32 + 1.
                record felt {
                    /// The backing type is `f32` which will be treated as a felt by the compiler.
            	/// We're basically hijacking the Wasm `f32` type and treat as felt.
                    inner: f32,
                }


                /// A group of four field elements in the Miden base field.
                record word {
                    a: felt,
            	b: felt,
            	c: felt,
            	d: felt,
                }

                /// A cryptographic digest representing a 256-bit hash value.
                /// This is a wrapper around `word` which contains 4 field elements.
                record digest {
                    inner: word
                }

                /// Unique identifier of an account.
                ///
                /// # Layout
                ///
                /// An `AccountId` consists of two field elements, where the first is called the prefix and the
                /// second is called the suffix. It is laid out as follows:
                ///
                /// prefix: [hash (56 bits) | storage mode (2 bits) | type (2 bits) | version (4 bits)]
                /// suffix: [zero bit | hash (55 bits) | 8 zero bits]
                record account-id {
                	prefix: felt,
            	suffix: felt
                }

                /// Creates a new account ID from a field element.
                //account-id-from-felt: func(felt: felt) -> account-id;

                /// Recipient of the note, i.e., hash(hash(hash(serial_num, [0; 4]), note_script_hash), input_hash)
                record recipient {
                    inner: word
                }

                record tag {
                    inner: felt
                }

                /// A fungible or a non-fungible asset.
                ///
                /// In protocol v0.14 assets are encoded as two words: an asset key and an asset value.
                ///
                /// The methodology for constructing fungible and non-fungible assets is described below.
                ///
                /// # Fungible assets
                /// - `key`: `[0, 0, faucet_id_suffix, faucet_id_prefix]`
                /// - `value`: `[amount, 0, 0, 0]`
                ///
                /// # Non-fungible assets
                /// - `key`: `[hash0, hash1, faucet_id_suffix, faucet_id_prefix]`
                /// - `value`: `DATA_HASH`
                record asset {
                    key: word,
                    value: word,
                }

                /// A validated fungible asset amount, at most 2^63 - 2^31.
                record asset-amount {
                    inner: felt
                }

                /// Account nonce
                record nonce {
                    inner: felt
                }

                /// A block height in the chain
                record block-number {
                    inner: felt
                }

                /// Account hash
                record account-hash {
                    inner: word
                }

                /// Block hash
                record block-hash {
                    inner: word
                }

                /// Storage value
                record storage-value {
                    inner: word
                }

                /// Account storage root
                record storage-root {
                    inner: word
                }

                /// Account code root
                record account-code-root {
                    inner: word
                }

                /// Commitment to the account vault
                record vault-commitment {
                    inner: word
                }

                /// An index of the created note
                record note-idx {
                    inner: felt
                }

                record note-type {
                    inner: felt
                }

                record note-execution-hint {
                    inner: felt
                }

            }
        }
    "#]],
    );
}

/// The pinned note-codec world WIT is duplicated into each package that embeds it, because
/// `include_str!` paths must not escape a published package's root. This test locks the copies
/// together; update all three files when the world changes.
#[test]
fn note_codec_wit_copies_are_identical() {
    let canonical = include_str!("../../../../../sdk/note-codec/wit/note-codec.wit");
    let macros_copy = include_str!("../../../../../sdk/note-codec/macros/wit/note-codec.wit");
    let compiler_copy = include_str!("../../../../../midenc-compile/wit/note-codec.wit");
    assert_eq!(canonical, macros_copy, "sdk/note-codec/macros/wit/note-codec.wit drifted");
    assert_eq!(canonical, compiler_copy, "midenc-compile/wit/note-codec.wit drifted");
}
