name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: |
        rustup update --no-self-update
        rustc --version
    - name: Install midenup and stable compiler components
      run: |
        cargo install --locked midenup && midenup init && midenup install 0.17.0 && midenc --version
        echo "MIDENUP_HOME=$(midenup show home)" >> "$GITHUB_ENV"
    - name: Run integration tests
      working-directory: integration
      run: |
        cargo test
