[package]
name = "miden-base-macros"
description = "Provides proc macro support for Miden rollup SDK"
version = "0.14.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
proc-macro = true
doctest = false

[features]
default = []
internal-wit-emit = ["dep:wit-component"]

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
miden-assembly-syntax.workspace = true
miden-mast-package.workspace = true
miden-protocol.workspace = true
miden-project.workspace = true
miden-debug-types.workspace = true
semver.workspace = true
toml.workspace = true
syn = { workspace = true, features = ["full"] }
heck.workspace = true
miden-formatting.workspace = true
midenc-frontend-wasm-metadata.workspace = true
wit-bindgen-core = "0.57"
wit-bindgen-rust = { version = "0.57", default-features = false }
wit-component = { workspace = true, optional = true }

[dev-dependencies]
# NOTE: Use local paths for dev-only dependency to avoid relying on crates.io during packaging
miden-assembly = { workspace = true, features = ["std"] }
miden-protocol = { workspace = true, features = ["std"] }
miden-field.workspace = true
miden-field-repr.workspace = true
wit-component.workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
additional-targets = ["wasm32-unknown-unknown", "wasm32-wasip1", "wasm32-wasip2"]
