[package]
name = "cargo-miden"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false # disable autodiscovery of tests

[[bin]]
name = "cargo-miden"

[[test]]
name = "integration"
path = "tests/mod.rs"

[dependencies]
midenc-compile.workspace = true
midenc-session.workspace = true
miden-diagnostics.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
anyhow.workspace = true
cargo-component = "0.5"
cargo-component-core = "0.5"
cargo_metadata = "0.18"
cargo-generate = "0.18"
semver = "1.0.20"
parse_arg = "0.1.4"
path-absolutize = "3.1.1"

[dev-dependencies]