package miden:p2id@1.0.0;


world notes-world {
    import miden:base/core-types@1.0.0;
    import miden:base/tx@1.0.0;
    import miden:base/account@1.0.0;
    import miden:base/note@1.0.0;

    import miden:basic-wallet/basic-wallet@1.0.0;

    export miden:base/note-script@1.0.0;
}
