[package]
name = "miden-hir"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cranelift-entity.workspace = true
intrusive-collections = "0.9"
miden-diagnostics.workspace = true
miden-hir-symbol = { path = "../hir-symbol" }
miden-hir-type = { path = "../hir-type" }
paste = "1.0"
rustc-hash.workspace = true
smallvec.workspace = true
thiserror.workspace = true
typed-arena = "2.0"
winter-math = { version = "0.6", default-features = false }
