[package]
name = "miden-hir"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[build-dependencies]
lalrpop = { version = "0.20", default-features = false }

[dependencies]
anyhow.workspace = true
cranelift-entity.workspace = true
intrusive-collections.workspace = true
lalrpop-util="0.20"
miden-assembly.workspace = true
miden-diagnostics.workspace = true
miden-hir-symbol.workspace = true
miden-hir-type.workspace = true
miden-parsing = "0.1"
petgraph = "0.6"
paste.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
thiserror.workspace = true
typed-arena = "2.0"
winter-math = { version = "0.6", default-features = false }
