[package]
name = "midenc-hir"
description = "High-level Intermediate Representation for Miden Assembly"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = ["base64/std", "compact_str/std", "rustc-demangle/std", "semver/std"]
debug_refcell = []
logging = ["dep:midenc-log", "std"]

[dependencies]
anyhow.workspace = true
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
bitflags.workspace = true
blink-alloc.workspace = true
compact_str.workspace = true
hashbrown.workspace = true
intrusive-collections.workspace = true
inventory.workspace = true
log.workspace = true
miden-core.workspace = true
midenc-log = { workspace = true, optional = true }
midenc-hir-symbol = { workspace = true, features = ["compact_str"] }
midenc-hir-type.workspace = true
midenc-hir-macros.workspace = true
midenc-session.workspace = true
paste.workspace = true
rustc-hash.workspace = true
rustc-demangle = "0.1.19"
semver.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
litcheck-filecheck.workspace = true
# NOTE: Use local paths for dev-only dependency to avoid relying on crates.io during packaging
midenc-expect-test = { path = "../tools/expect-test" }
midenc-log = { path = "../midenc-log" }
pretty_assertions.workspace = true

[package.metadata.cargo-shear]
ignored-paths = [
    "src/dialects/builtin/attributes/map.rs",
    "src/dialects/builtin/attributes/set.rs",
]
