[package]
name = "midenc-integration-tests"
# Never published; this version is deliberately frozen and meaningless.
version = "0.1.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
syn = { workspace = true, features = ["full"] }
quote.workspace = true
log.workspace = true
miden-assembly.workspace = true
miden-core-lib = { workspace = true, features = ["std"] }
midenc-expect-test.workspace = true
miden-core = { workspace = true, features = ["testing"] }
miden-mast-package.workspace = true
miden-protocol = { workspace = true, features = ["std"] }
miden-processor.workspace = true
miden-debug = { workspace = true, features = ["proptest", "std"] }
midenc-dialect-arith.workspace = true
midenc-dialect-cf.workspace = true
midenc-dialect-hir.workspace = true
midenc-dialect-scf.workspace = true
midenc-dialect-wasm.workspace = true
midenc-frontend-wasm.workspace = true
midenc-frontend-wasm-metadata.workspace = true
midenc-hir = { workspace = true, features = ["logging"] }
midenc-hir-eval.workspace = true
midenc-session.workspace = true
midenc-integration-test-support.workspace = true
num-traits = "0.2"
proptest.workspace = true
sha2.workspace = true

[dev-dependencies]
# NOTE: Use local paths for dev-only dependency to avoid relying on crates.io during packaging
blake3 = "1.5"
cargo_metadata = "0.19"
concat-idents = "1.1"
libloading = "0.8"
wasmi = "1.1.0"
wat.workspace = true
