(component
  (core module (;0;)
    (table (;0;) 1 1 funcref)
    (memory (;0;) 16)
    (global $__stack_pointer (;0;) (mut i32) i32.const 1048576)
    (export "memory" (memory 0))
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (component (;0;)
    (type (;0;) (record (field "inner" float64)))
    (import "import-type-felt" (type (;1;) (eq 0)))
    (type (;2;) (record (field "inner" 1)))
    (import "import-type-account-id" (type (;3;) (eq 2)))
    (type (;4;) (func (param "felt" 1) (result 3)))
    (import "import-func-account-id-from-felt" (func (;0;) (type 4)))
    (type (;5;) (record (field "inner" float64)))
    (export (;6;) "felt" (type 5))
    (type (;7;) (tuple 6 6 6 6))
    (export (;8;) "word" (type 7))
    (type (;9;) (record (field "inner" 6)))
    (export (;10;) "account-id" (type 9))
    (export (;11;) "recipient" (type 8))
    (export (;12;) "tag" (type 6))
    (type (;13;) (record (field "inner" 8)))
    (export (;14;) "core-asset" (type 13))
    (type (;15;) (func (param "felt" 6) (result 10)))
    (export (;1;) "account-id-from-felt" (func 0) (func (type 15)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-account-id-from-felt" (func 0))
      (with "import-type-felt" (type 0))
      (with "import-type-account-id" (type 1))
    )
  )
  (export (;1;) "miden:base/core-types@1.0.0" (instance 0))
  (alias export 1 "felt" (type (;3;)))
  (alias export 1 "account-id" (type (;4;)))
  (alias export 1 "word" (type (;5;)))
  (component (;1;)
    (type (;0;) (record (field "inner" float64)))
    (import "import-type-felt" (type (;1;) (eq 0)))
    (type (;2;) (record (field "inner" 1)))
    (import "import-type-account-id" (type (;3;) (eq 2)))
    (type (;4;) (tuple 1 1 1 1))
    (import "import-type-word" (type (;5;) (eq 4)))
    (export (;6;) "felt" (type 1))
    (export (;7;) "account-id" (type 3))
    (export (;8;) "word" (type 5))
    (type (;9;) (record (field "asset" 7) (field "amount" u64)))
    (export (;10;) "fungible-asset" (type 9))
    (export (;11;) "non-fungible-asset" (type 8))
    (type (;12;) (variant (case "fungible" 10) (case "non-fungible" 11)))
    (export (;13;) "asset" (type 12))
  )
  (instance (;2;) (instantiate 1
      (with "import-type-felt" (type 3))
      (with "import-type-account-id" (type 4))
      (with "import-type-word" (type 5))
    )
  )
  (export (;3;) "miden:base/types@1.0.0" (instance 2))
)