(component
  (core module (;0;)
    (table (;0;) 1 1 funcref)
    (memory (;0;) 16)
    (global $__stack_pointer (;0;) (mut i32) i32.const 1048576)
    (export "memory" (memory 0))
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (component (;0;)
    (type (;0;) u64)
    (export (;1;) "felt" (type 0))
    (type (;2;) (tuple 1 1 1 1))
    (export (;3;) "word" (type 2))
    (export (;4;) "account-id" (type 1))
    (export (;5;) "recipient" (type 3))
    (export (;6;) "tag" (type 1))
    (type (;7;) (record (field "asset" 4) (field "amount" u64)))
    (export (;8;) "fungible-asset" (type 7))
    (export (;9;) "non-fungible-asset" (type 3))
    (type (;10;) (variant (case "fungible" 8) (case "non-fungible" 9)))
    (export (;11;) "asset" (type 10))
    (type (;12;) (list 1))
    (export (;13;) "note-inputs" (type 12))
  )
  (instance (;0;) (instantiate 0))
  (export (;1;) "miden:base/types@1.0.0" (instance 0))
)