[package]
name = "midenc-codegen-masm"
description = "Miden Assembly backend for the Miden compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
doctest = false

[features]
default = ["std"]
std = [
    "miden-assembly/std",
    "miden-utils-sync/std",
    "midenc-hir/std",
    "midenc-dialect-hir/std",
    "petgraph/std",
]

[dependencies]
anyhow.workspace = true
inventory.workspace = true
log.workspace = true
miden-assembly.workspace = true
miden-assembly-syntax.workspace = true
miden-core.workspace = true
miden-mast-package.workspace = true
miden-processor.workspace = true
miden-utils-sync.workspace = true
midenc-hir.workspace = true
midenc-hir-analysis.workspace = true
midenc-dialect-arith.workspace = true
midenc-dialect-cf.workspace = true
midenc-dialect-hir.workspace = true
midenc-dialect-scf.workspace = true
midenc-dialect-ub.workspace = true
midenc-dialect-wasm.workspace = true
midenc-session.workspace = true
petgraph.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
# NOTE: Use local paths for dev-only dependency to avoid relying on crates.io during packaging
itertools = "0.14.0"
miden-debug = { workspace = true, features = ["std"] }
midenc-expect-test = { path = "../../tools/expect-test" }
midenc-hir = { path = "../../hir", features = ["logging"] }
proptest.workspace = true

[build-dependencies]
miden-assembly = { workspace = true, features = ["std"] }
midenc-log.workspace = true
midenc-session = { workspace = true, features = ["std"] }
