[package]
name = "miden"
description = "Miden SDK"
version = "0.14.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]
test = false
doctest = false

[dependencies]
miden-sdk-alloc = { version = "0.14.0", path = "../alloc" }
miden-stdlib-sys.workspace = true
miden-base = { version = "0.14.0", path = "../base" }
miden-base-macros = { version = "0.14.0", path = "../base-macros" }
miden-base-sys.workspace = true
miden-field-repr.workspace = true
miden-field = { workspace = true, default-features = false }
miden-tx-script-args = { workspace = true, features = ["miden-vm-guest"] }
wit-bindgen = { workspace = true }

[features]
default = []
internal-wit-emit = ["miden-base-macros/internal-wit-emit"]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
additional-targets = ["wasm32-unknown-unknown", "wasm32-wasip1", "wasm32-wasip2"]
