[package]
name = "miden-sdk"
description = "Miden SDK"
version = "0.0.1"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
miden-stdlib-sys = { path = "../stdlib-sys" }
miden-base-sys = { path = "../base-sys", features = ["bindings"] }
