[package]
name = "miden-sdk"
description = "Miden SDK"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
miden-sdk-alloc = { version = "0.0.5", path = "../alloc" }
miden-stdlib-sys = { version = "0.0.5", path = "../stdlib-sys" }
miden-base-sys = { version = "0.0.5", path = "../base-sys", features = ["bindings"] }
