[package]
name = "miden-sdk"
description = "Miden SDK"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
miden-sdk-types = { path = "../types" }
miden-sdk-tx-kernel = { path = "../tx-kernel" }
