[fundamental]
false = { id = 0 }
true = { id = 1 }
empty = { value = "" }

[keywords]
kernel = {}
module = {}
internal = {}
odr = {}
external = {}
extern = {}
pub = {}
fn = {}
cc = {}
fast = {}
sret = {}
zext = {}
sext = {}
trunc = {}
ret = {}
call = {}
syscall = {}
br = {}
condbr = {}
switch = {}
test = {}
load = {}
memcpy = {}
asm = {}
min = {}
max = {}
exp = {}
and = {}
band = {}
or = {}
bor = {}
xor = {}
bxor = {}
eq = {}
neq = {}
gt = {}
gte = {}
lt = {}
lte = {}
store = {}
inv = {}
pow2 = {}
not = {}
bnot = {}
popcnt = {}
is_odd = { value = "is_odd" }
cast = {}
ptrtoint = {}
inttoptr = {}
neg = {}
select = {}
assert = {}
assertz = {}
alloca = {}
unreachable = {}
i1 = {}
i8 = {}
u8 = {}
i16 = {}
u16 = {}
i32 = {}
u32 = {}
i64 = {}
u64 = {}
i128 = {}
u128 = {}
u256 = {}
f64 = {}
felt = {}
mut = {}
as = {}
id = {}
global = {}
symbol = {}
iadd = {}
const = {}

[passes]
inline_blocks = { value = "inline-blocks" }
split_critical_edges = { value = "split-critical-edges" }
treeify = { value = "treeify" }

[attributes]
entrypoint = {}

[dialects]
hir = {}
