[package]
name = "miden-note-schema-codegen"
description = "Rust code generator for Miden note storage schemas"
version = "0.14.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
heck.workspace = true
miden-note-schema.workspace = true
proc-macro2.workspace = true
quote.workspace = true

[dev-dependencies]
prettyplease = { workspace = true }
syn.workspace = true
