package miden:basic-wallet@1.0.0;

use miden:base/core-types@1.0.0;
use miden:base/types@1.0.0;
use miden:base/tx@1.0.0;
use miden:base/account@1.0.0;

interface basic-wallet {
    use core-types.{core-asset, tag, recipient};

    receive-asset: func(core-asset: core-asset);
    send-asset: func(core-asset: core-asset, tag: tag, recipient: recipient);
}

world basic-wallet-world {
    import account;
    import tx;
    export basic-wallet;
}
