package miden:basic-wallet@1.0.0;

use miden:base/core-types@1.0.0;

interface basic-wallet {
    use core-types.{core-asset, tag, recipient, note-type, felt};

    receive-asset: func(core-asset: core-asset);
    send-asset: func(core-asset: core-asset, tag: tag, note-type: note-type, recipient: recipient);

    test-felt-intrinsics: func(a: felt, b: felt) -> felt;
    test-stdlib: func(input: list<u8>) -> list<u8>;
}

world basic-wallet-world {
    include miden:core-import/all@1.0.0;

    export basic-wallet;
}