[package]
name = "miden-sdk"
version = "0.1.0"
rust-version = "1.71"
authors = ["Miden Team"]
description = "Miden SDK"
license = "MIT"
edition = "2021"
publish = false

# To keep it out of the root workspace since it cannot be built for a non-Wasm target
[workspace]

[dependencies]
cargo-component-bindings = "0.6.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:miden"

[package.metadata.component.dependencies]

[profile.release]
panic = "abort"