name: book

on:
  push:
    branches:
      - main
      - next

jobs:
  publish_docs:
    name: publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup update --no-self-update
          rustc --version
      - name: Install cargo-make
        run: |
          cargo install cargo-make --force
      - name: Build
        run: |
          cargo make docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs/site
