name: CI

on:
  push:
    paths-ignore:
    - '*.md'
  pull_request:
    paths-ignore:
    - '*.md'

env:
  CARGO_MAKE_TOOLCHAIN: nightly-2023-08-23

jobs:
  compiler:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.CARGO_MAKE_TOOLCHAIN }}
        override: true
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.CARGO_MAKE_TOOLCHAIN }}
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-make
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: build
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: test
