name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

env:
  CARGO_MAKE_TOOLCHAIN: nightly-2024-03-10

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.CARGO_MAKE_TOOLCHAIN }}
        override: true
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.CARGO_MAKE_TOOLCHAIN }}
    - name: Run release-plz
      uses: MarcoIeni/release-plz-action@v0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
