# Runs `release-plz release` only after the release PR is merged to the main branch 
# see `release_always = false` in `release-plz.toml` 
# Which publishes any unpublished crates.
# Does nothing if all crates are already published (i.e. have their versions on crates.io).
# Does not create/update release PRs.
# The crate version bumping and changelog generation is done manually via the `release-plz release_pr` CLI command.
# Which creates the PR with the proposed changes and when the PR is merged this action will publish the crates.
name: release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

env:
  CARGO_MAKE_TOOLCHAIN: nightly-2024-03-10

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.CARGO_MAKE_TOOLCHAIN }}
        override: true
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.CARGO_MAKE_TOOLCHAIN }}
    - name: Run release-plz
      uses: MarcoIeni/release-plz-action@v0.5
      with:
        # Only run the `release` command. 
        # The release PR is created manually via the `release-plz release_pr` CLI command.
        # see https://release-plz.ieni.dev/docs/usage/release for more details
        command: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
